// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	depsmanager "depsmanager"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// DeleteProject provides a mock function with given fields: ctx, projectName, version
func (_m *Storage) DeleteProject(ctx context.Context, projectName string, version string) error {
	ret := _m.Called(ctx, projectName, version)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, projectName, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListProjectDependencies provides a mock function with given fields: ctx, projectName, version
func (_m *Storage) ListProjectDependencies(ctx context.Context, projectName string, version string) ([]depsmanager.Dependency, error) {
	ret := _m.Called(ctx, projectName, version)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectDependencies")
	}

	var r0 []depsmanager.Dependency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]depsmanager.Dependency, error)); ok {
		return rf(ctx, projectName, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []depsmanager.Dependency); ok {
		r0 = rf(ctx, projectName, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]depsmanager.Dependency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, projectName, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProjects provides a mock function with given fields: ctx
func (_m *Storage) ListProjects(ctx context.Context) ([]depsmanager.Project, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 []depsmanager.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]depsmanager.Project, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []depsmanager.Project); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]depsmanager.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreDependencies provides a mock function with given fields: ctx, deps
func (_m *Storage) StoreDependencies(ctx context.Context, deps depsmanager.ProjectDependencyRecord) error {
	ret := _m.Called(ctx, deps)

	if len(ret) == 0 {
		panic("no return value specified for StoreDependencies")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, depsmanager.ProjectDependencyRecord) error); ok {
		r0 = rf(ctx, deps)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProject provides a mock function with given fields: ctx, deps
func (_m *Storage) UpdateProject(ctx context.Context, deps depsmanager.ProjectDependencyRecord) error {
	ret := _m.Called(ctx, deps)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, depsmanager.ProjectDependencyRecord) error); ok {
		r0 = rf(ctx, deps)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
